require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5.0

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

Metrics/LineLength:
  Max: 122

Metrics/MethodLength:
  Max: 16


Metrics/ModuleLength:
   Enabled: false

Style/DocumentationMethod:
  Description: 'Public methods.'
  Enabled: true
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'




# inherit_from: .rubocop_todo.yml